export const ButtonTypes = {
    SQUARE: 'btn-square',
    BLACK_BORDER: 'btn-black-border',
    DEFAULT: 'btn-default',
    WHITE: 'btn-white',
    BD_GREEN_HOVER: 'btn-bd-green-hover',
    SELECT: 'btn-select',
    GREEN_900: 'btn-green-900',
    BLACK: 'btn-black',
    MD: 'btn-md',
    SQUARE_SHAPE: 'shape-square',
    LINK: 'btn-link',
    PINK: 'btn-pink',
    LINK_INTER: 'btn-link-inter',
    ROUND_ICON: 'btn-round-icon',
    SQUARE_GREEN: 'btn-square-green',
    GREEN_FULL: 'btn-green-full',
    MEDIA: 'btn-media',
    LOGIN_GOOGLE: 'btn-login-google',
    TAG: 'btn-tag',
    NEWSLETTER: 'btn-newsletter',
    CART: 'btn-cart',
    EXPLORER: 'btn-explorer',
    BORDER: 'btn-border',
    // Add other button types as needed
};  