import { GoogleTagManager } from '@next/third-parties/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <GoogleTagManager gtmId="G-EDXZVWFRV6" />
    </html>
  )
}
